name: auto-rccar
dependencies:
    - python
    - numpy
    - matplotlib
    - jupyter
    - scikit-learn
    - cython
    - pip:
        - pygame
        - pyserial
        - opencv-python
        # - spidev
        # uncomment above when running on rpi